ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER urbnluxe IDENTIFIED BY "12345678"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER urbnluxe QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO urbnluxe;
GRANT "RESOURCE" TO urbnluxe;
ALTER USER urbnluxe DEFAULT ROLE "RESOURCE";