ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER TallerBD IDENTIFIED BY "12345678"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER TallerBD QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO TallerBD;
GRANT "RESOURCE" TO TallerBD;
ALTER USER TallerBD DEFAULT ROLE "RESOURCE";